apiVersion: v1
kind: Service
metadata:
  name: {{ include "memgraph.fullname" . }}
  labels:
    {{- include "memgraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: {{ .Values.service.protocol }}
      name: bolt
  selector:
    {{- include "memgraph.selectorLabels" . | nindent 4 }}
