apiVersion: v1
kind: Service
metadata:
  name: {{ include "memgraph.fullname" . }}
  labels:
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: {{ .Values.service.protocol }}
      name: bolt
  selector:
    app.kubernetes.io/name: memgraph
