# templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "memgraph.fullname" . }}
  labels:
    app.kubernetes.io/name: memgraph
    app.kubernetes.io/managed-by: Helm 
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "memgraph.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: memgraph
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
         app.kubernetes.io/name: memgraph
    spec:
      securityContext:
      volumes:
      {{ if .Values.persistentVolumeClaim.storagePVC }}
        - name: memgraph-lib-storage
          persistentVolumeClaim:
            claimName: {{ include "memgraph.fullname" . }}-lib-storage
      {{end}}
      {{ if .Values.persistentVolumeClaim.logPVC }}
        - name: memgraph-log-storage
          persistentVolumeClaim:
            claimName: {{ include "memgraph.fullname" . }}-log-storage
      {{end}}
      containers:
        - name: memgraph
          image: {{ .Values.image }}
          args: ["--also-log-to-stderr=true"]
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
          ports:
            - name: memgraph
              containerPort: {{ .Values.service.port }}
          volumeMounts:
          {{ if .Values.persistentVolumeClaim.storagePVC }}
            - name: memgraph-lib-storage
              mountPath: /var/lib/memgraph
          {{end}}
          {{ if .Values.persistentVolumeClaim.logPVC }}
            - name: memgraph-log-storage
              mountPath: /var/log/memgraph
          {{end}}
