apiVersion: v2
name: memgraph
home: https://memgraph.com/
type: application
version: 0.1.1
appVersion: "1.16.0"
description: MemgraphDB Helm Chart 
keywords: 
 - graph 
 - database 
 - cypher
 - analytics
sources: 
  - https://github.com/memgraph/memgraph

maintainers:
 - name: Memgraph 
   email: tech@memgraph.com
