

image: memgraph/memgraph:latest

replicaCount: 1

service:
  type: NodePort
  port: 7687
  targetPort: 7687
  protocol: TCP

persistentVolumeClaim:
  storagePVC: true
  storagePVCSize: 1Gi
  logPVC: true
  logPVCSize: 256Mi