name: Chart Validation
on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Validate Helm Charts
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo update
          helm lint memgraph/

      - name: Render Helm Templates
        run: |
          helm template memgraph/ > rendered-templates.yaml

      - name: Install kubeval
        run: |
          curl -LO "https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz"
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin/

      - name: Validate Rendered Templates
        run: |
          kubeval rendered-templates.yaml
