name: Sync Main with gh-pages

on:
  workflow_run:
    workflows: ["Chart Validation"]
    types:
      - completed

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync with gh-pages
        run: |
          git config user.name "katarinasupe"
          git config user.email "supe.katarina@gmail.com"
          git checkout gh-pages
          git merge --ff-only main
          git push origin gh-pages
